#!/usr/bin/env python

from zensols.cli import CliHarness


if (__name__ == '__main__'):
    args: str = ''
    model = {
        0: None,
        1: 'inference',
        2: 'parse-xfm-base-lp',
        3: 'parse-t5-lp',
        4: 'parse-spring-lp',
        5: 'generate-t5wtense-lp',
    }[0]
    if model is not None:
        args = f' -c example/train/{model}.conf'
    harness = CliHarness(
        src_dir_name='src/python',
        app_factory_class='zensols.amr.ApplicationFactory',
        proto_args='proto' + args,
        proto_factory_kwargs={'reload_pattern': r'^zensols\.amr\.(?!annotate)'}
    )
    harness.run()
