#!/usr/bin/env python

from zensols.cli import CliHarness


if (__name__ == '__main__'):
    import zensols.deepnlp.transformer as dnt
    dnt.normalize_huggingface_logging()
    dnt.turn_off_huggingface_downloads()
    model = {
        0: 'xfm-base-lp',
        1: 't5-lp',
        2: 'spring-lp',
    }[1]
    harness = CliHarness(
        src_dir_name='src/python',
        app_factory_class='zensols.amr.ApplicationFactory',
        proto_args=f'proto -c etc/{model}.conf',
        proto_factory_kwargs={'reload_pattern': r'^zensols\.amr\.(?!annotate)'}
    )
    harness.run()
