## makefile automates the build and deployment for python projects


## Build system
#
PROJ_TYPE =		python
PROJ_MODULES =		python/doc python/package python/deploy

# additional cleanup
ADD_CLEAN +=		amr-bank-struct-v3.0-scored.csv \
			corpus/amr-bank-struct-v3.0-parsed.txt
ADD_CLEAN_ALL +=	amr_graph models
CLEAN_DEPS +=		cleanexample
CLEAN_ALL_DEPS +=	cleanalldep
VAPORIZE_DEPS +=	vaporizedep

# targets for the pytestall target
PY_TEST_ALL_TARGETS +=	testparse testplot testexample


## Project build
#
# file, models and entry point
MODEL_CONF_DIR = 	train-config
MODEL_FILE =		corpus/amr-bank-struct-v3.0.txt
EVAL_FILE = 		target/corp/stage/dev/dev.txt
INF_CONF = 		resources/model/inference.conf
IT_PARSE_GOLD =		test-resources/inttest-should/parse.txt
IT_EX_GOLD =		test-resources/inttest-should/examples.txt


## Project data
#
# text to parse for run examples
TEST_TEXT = 		"Barack Obama is an American politician who served as the 44th president of the United States from 2009 to 2017. A member of the Democratic Party, he was the first African-American president of the United States."


## Definitions
#
define arun
	@$(MAKE) $(PY_MAKE_ARGS) pyharn \
		BUILD_INFO=0 PY_INVOKE_ARG='-e testcur' ARG='$(1)'
endef



## Includes
#
include ./zenbuild/main.mk


## Targets
#
# test parsing text
.PHONY:			testparsewrite
testparsewrite:
			@$(call loginfo,writing parse gold $(IT_PARSE_GOLD)...)
			@$(MAKE) clean
			@$(call arun,parse -c test-resources/test.conf \
			  $(TEST_TEXT)) > $(IT_PARSE_GOLD)

.PHONY:			testparse
testparse:
			@$(MAKE) clean
			@$(call loginfo,testing parse $(IT_PARSE_GOLD)...)
			@$(call arun,parse -c test-resources/test.conf \
				--level warn $(TEST_TEXT)) | \
			  diff - $(IT_PARSE_GOLD) || \
			    exit 1

# test plotting text
.PHONY:			testplot
testplot:
			@$(call loginfo,testing plots...)
			@$(MAKE) clean
			$(call arun,plot $(TEST_TEXT))
			@if [ ! `ls -l amr_graph/barack*/*.pdf | wc -l` -eq 2 ] ; then \
				echo "error: missing plot PDF files" ; \
			fi
			@if [ ! `ls -l amr_graph/barack*/*.txt | wc -l` -eq 3 ] ; then \
				echo "error: missing AMR text output files" ; \
			fi

# integration test all examples
.PHONY:			testexamplewrite
testexamplewrite:
			@$(call loginfo,(re)writing testing examples gold...)
			@$(MAKE) clean
			@( for i in example/*.py ; \
			  do PYTHONPATH=src $(PY_PX_BIN) run \
				$(PY_INVOKE_ARG) python ./$$i ; \
			  done ) > $(IT_EX_GOLD)

.PHONY:			testexample
testexample:
			@$(call loginfo,testing examples...)
			@$(MAKE) clean pyinit
			@( for i in example/*.py ; \
			  do PYTHONPATH=src $(PY_PX_BIN) run \
				$(PY_INVOKE_ARG) python ./$$i ; \
			  done ) | \
			  diff - $(IT_EX_GOLD) || \
			  exit 1

# generate AMR plots of the little prince and the biomedical corpora
.PHONY:			renderexamples
renderexamples:
			@$(call arun,plotfile $(MODEL_FILE))

# train on the little prince corpus
.PHONY:			trainmodel
trainmodel:
			@$(call arun,--config $(MODEL_CONF_DIR)/parse-spring.conf
				train)

# inference a new trained model
.PHONY:			testmodel
testmodel:
			@$(call arun,--config $(INF_CONF) parse $(TEST_TEXT))

# evaluation model "EVAL_MODEL"
.PHONY:			evalmodel
evalmodel:
			@$(call arun,prep)
			@$(call arun,parsefile $(EVAL_FILE) --config $(INF_CONF) \
				--limit 50 \
				--override amr_default.parse_model=$(EVAL_MODEL) )
			@$(call arun,score $(EVAL_FILE) --config $(INF_CONF) \
				--override amr_default.parse_model=$(EVAL_MODEL)

# evaluate the corpus on the trained little prince corpus (test)
.PHONY:			evalspring
evalspring:
			@$(MAKE)EVAL_MODEL=zsl_spring evalmodel

# additional clean up using the harness/API (data dir)
.PHONY:			cleanalldep
cleanalldep:
			rm -fr data

# clean data generated by examples
.PHONY:			cleanexample
cleanexample:
			rm -fr example/data

# remove the ./data and ./corpus dir
.PHONY:			vaporizedep
vaporizedep:
			rm -rf corpus
